// Point the mobile app at this machine's LAN address, automatically.
//
//   npm start            <- runs this first (prestart hook), then expo start
//   node scripts/lan-ip.js   <- run it alone to just see what it picks
//   LAN_IP=10.0.2.2 node scripts/lan-ip.js   <- override, e.g. for an emulator
//
// A physical device cannot use "localhost" for the backend — it is a different
// machine — so the API URL has to carry a real address. That is why this used
// to be a hardcoded IP in .env, which went stale every time the wifi changed.
//
// The web app does not need any of this: frontend/vite.config.js proxies /api
// and /socket.io so the browser sees one origin. This file exists only because
// a phone cannot be proxied.

const fs = require('fs');
const os = require('os');
const path = require('path');

const PORT = Number(process.env.PORT) || 5000;
const TIMEOUT_MS = 1500;

// Docker, WSL, Hyper-V and the VM tools all publish private IPv4 addresses that
// are reachable from nowhere a phone can see. Prefer a real adapter.
const VIRTUAL = /vethernet|docker|wsl|hyper-v|virtualbox|vmware|loopback|pseudo/i;

const isPrivate = (ip) => {
  if (ip.startsWith('10.')) return true;
  if (ip.startsWith('192.168.')) return true;
  const m = ip.match(/^172\.(\d+)\./);
  if (m) {
    const second = Number(m[1]);
    return second >= 16 && second <= 31;
  }
  return false;
};

const candidates = () => {
  const override = (process.env.LAN_IP || '').trim();
  if (override) return [{ name: 'LAN_IP override', address: override, forced: true }];

  const found = [];
  for (const [name, addrs] of Object.entries(os.networkInterfaces())) {
    for (const a of addrs || []) {
      // Node 18+ reports family as the string 'IPv4'; older builds use 4.
      const isV4 = a.family === 'IPv4' || a.family === 4;
      if (!isV4 || a.internal) continue;
      if (!isPrivate(a.address)) continue;
      found.push({ name, address: a.address, virtual: VIRTUAL.test(name) });
    }
  }
  // Real adapters first, so a real adapter wins over a virtual one that also
  // happens to answer the health check.
  return found.sort((a, b) => Number(a.virtual) - Number(b.virtual));
};

const reachable = async (address) => {
  const url = `http://${address}:${PORT}/api/v1/health`;
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(TIMEOUT_MS) });
    return res.ok;
  } catch {
    return false;
  }
};

const run = async () => {
  const list = candidates();

  if (list.length === 0) {
    console.error('\n  No private IPv4 address found on this machine.');
    console.error('  Connect to the wifi the phone is on, or set LAN_IP explicitly:\n');
    console.error('    LAN_IP=<address> node scripts/lan-ip.js\n');
    process.exit(1);
  }

  console.log('\n  Candidate addresses:');
  for (const c of list) {
    // An explicit LAN_IP is trusted without a reachability check. The point of
    // the override is "I know better than your detection" — the Android
    // emulator's 10.0.2.2 is an alias that resolves to the host only from
    // inside the emulator, so nothing answers on the host's own stack and a
    // health check here would reject a perfectly good configuration.
    if (c.forced) {
      console.log(`    overridden  ${c.address.padEnd(16)} (${c.name}, not health-checked)`);
      writeEnv(c);
      return;
    }

    const ok = await reachable(c.address);
    console.log(`    ${ok ? 'reachable' : 'no answer '}  ${c.address.padEnd(16)} (${c.name})`);
    if (ok) {
      writeEnv(c);
      return;
    }
  }

  const first = list[0];
  console.error(`\n  Nothing answered on port ${PORT}.`);
  console.error(`  The backend is not reachable at ${first.address}:${PORT}.`);
  console.error(`  Start it first:  cd backend && npm run dev\n`);
  console.error('  If the backend is on another address, set it explicitly:');
  console.error(`    LAN_IP=<address> node scripts/lan-ip.js\n`);
  process.exit(1);
};

const writeEnv = ({ address }) => {
  const target = path.join(__dirname, '..', '.env.local');
  const body = [
    '# Generated by scripts/lan-ip.js on every `npm start`. Do not edit by hand.',
    '# Ignored by git (mobile/.gitignore: .env*.local).',
    `EXPO_PUBLIC_API_URL=http://${address}:${PORT}/api/v1`,
    `EXPO_PUBLIC_SOCKET_URL=http://${address}:${PORT}`,
    '',
  ].join('\n');

  const previous = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
  if (previous === body) {
    console.log(`\n  Using ${address}:${PORT} (unchanged)\n`);
    return;
  }

  fs.writeFileSync(target, body);
  console.log(`\n  Using ${address}:${PORT} -> .env.local`);
  console.log('  Make sure the phone is on the same wifi.\n');
};

run();
